# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

parameters:
  #Agent name allows us to match a capability on a local agent, effectively targeting a specific build machine
- name: 'DeveloperName'
  displayName: 'Specifty target dev whose agent to use, or Any'
  type: string
  default: 'Any'

jobs:
- job: DeployPackagesNuget

  pool:
    name: 'PTBuildMachines'
    ${{ if ne(parameters.DeveloperName, 'Any') }}:
        demands:
        - Developer -equals ${{ parameters.DeveloperName }} 
  steps:
  # - task: DownloadBuildArtifacts@1
  #   inputs:
  #     buildType: 'specific'
  #     project: '01e4fd74-d148-468c-8d24-430c03a091d9'
  #     pipeline: '42' # 12.0 Software
  #     buildVersionToDownload: 'latest'
  #     downloadType: 'single'
  #     artifactName: 'drop'
  #     downloadPath: '$(System.ArtifactsDirectory)'

  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: 'specific'
      project: '01e4fd74-d148-468c-8d24-430c03a091d9'
      pipeline: '52' # 12.0 Server Manager
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      packagesToPush: '$(System.ArtifactsDirectory)\drop\*.nupkg;'
      publishVstsFeed: '4474bea0-86f0-40e8-b558-4e2ff8129a7d'
